version: '3.3'
services:
  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.3
    # environment:
      # - INFLUXDB_REPORTING_DISABLED=true
      # - INFLUXDB_BUCKET=energy
      # - INFLUXDB_ADMIN_USER=root
      # - INFLUXDB_ADMIN_PASSWORD=p455w0rd
      # - INFLUXDB_USER=energy
      # - INFLUXDB_USER_PASSWORD=energy123
    ports:
      - "8086:8086"
    # volumes:
    #   - "influxdb:/var/lib/influxdb"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
networks:
  default:
    attachable: true
volumes:
  influxdb:
  chronograf:
