version: "3.3"
services:
    influxdb:
        image: quay.io/influxdb/influxdb:v2.0.3
        ports:
            - "8086:8086"
        volumes:
            - "influxdb:/var/lib/influxdb"
    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"
        depends_on:
            - influxdb
networks:
    default:
        attachable: true
volumes:
    influxdb:
